title: Jayit Ghosh
description: Currently working as a Data Analyst at CKUENS Analytics Pvt. Ltd. <br>
<p> Number - +91 8780783024  <br>
LinkedIn - https://www.linkedin.com/in/jayitghosh/  <br>
Github - https://github.com/jaegarbomb/ <br>
</p>
theme: jekyll-theme-slate
